pipeline:
  name: demo-cicd
  identifier: democicd
  projectIdentifier: DemoProject
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GithubConnector
        build: <+input>
  stages:
    - stage:
        name: publish
        identifier: publish
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: KubernetesConnector
              namespace: "harness-delegate-ng "
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPush
                  identifier: BuildAndPush
                  spec:
                    connectorRef: account.harnessImage
                    repo: avijitinorg/harness-demo
                    tags:
                      - latest
                    envVariables:
                      docker-username: avijitinorg
