pipeline:
  name: demo-cicd
  identifier: democicd
  projectIdentifier: DemoProject
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GithubConnector
        build: <+input>
  stages:
    - stage:
        name: publish
        identifier: publish
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            useFromStage: build
          execution:
            steps:
              - step:
                  type: Run
                  name: publishing to docker hub
                  identifier: publishing_to_docker_hub
                  spec:
                    connectorRef: account.harnessImage
                    image: docker:latest
                    shell: Sh
                    command: |-
                      sudo systemctl start docker
                      docker build -t avijitinorg/harness-demo .
                      docker push avijitinorg/harness-demo
