pipeline:
  name: deployment
  identifier: deployment
  projectIdentifier: DemoProject
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GithubConnector
        build: <+input>
  stages:
    - stage:
        name: echo message
        identifier: echo_message
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: KubernetesConnector
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Sh
                    command: echo 'message'
